# Generated by Django 3.2.6 on 2021-08-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0002_alter_notice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
